workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "NFC-Example.xcodeproj"
        XCODE_SCHEME: "NFC-Example"
      xcode: 14.3
      cocoapods: default
      groups:
        - ios_credentials
    scripts:
      - name: Set up environment
        script: |
          mkdir -p ~/Library/Developer/Xcode/DerivedData
          mkdir -p build/ios/archive
          mkdir -p build/ios/ipa
          pwd
          ls -la
      - name: Update project settings
        script: |
          # Update deployment target
          /usr/libexec/PlistBuddy -c "Set :objects:*:buildSettings:IPHONEOS_DEPLOYMENT_TARGET 12.0" "$XCODE_WORKSPACE/project.pbxproj"
          
          # Update Swift version
          /usr/libexec/PlistBuddy -c "Set :objects:*:buildSettings:SWIFT_VERSION 5.0" "$XCODE_WORKSPACE/project.pbxproj"
          
          # Update project format version
          /usr/libexec/PlistBuddy -c "Set :objectVersion 54" "$XCODE_WORKSPACE/project.pbxproj"
      - name: Build IPA
        script: |
          # Clean DerivedData
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          
          # Clean and build
          xcodebuild clean -project "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -verbose
          
          # Archive
          xcodebuild archive \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$PWD/build/ios/archive/NFC-Example.xcarchive" \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE="" \
            IPHONEOS_DEPLOYMENT_TARGET=12.0 \
            SWIFT_VERSION=5.0 \
            SWIFT_OPTIMIZATION_LEVEL=-Onone \
            COMPILER_INDEX_STORE_ENABLE=NO \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=NO \
            VALIDATE_WORKSPACE=NO \
            IBSC_MODULE="NFC_Example" \
            IBSC_COMPILER_PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ibtool" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            BUILD_ACTIVE_RESOURCES_ONLY=NO \
            GCC_OPTIMIZATION_LEVEL=0 \
            SWIFT_ACTIVE_COMPILATION_CONDITIONS="DEBUG" \
            GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1" \
            CONFIGURATION=Release \
            -destination 'generic/platform=iOS' \
            -verbose
          
          # Check archive exists
          ls -la "$PWD/build/ios/archive"
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/ios/archive/NFC-Example.xcarchive" \
            -exportPath "$PWD/build/ios/ipa" \
            -exportOptionsPlist ios/exportOptions.plist \
            -allowProvisioningUpdates \
            -verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log 