workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "NFC-Example.xcodeproj"
        XCODE_SCHEME: "NFC-Example"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build IPA
        script: |
          xcodebuild archive \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/archive/NFC-Example.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/NFC-Example.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log 