workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "NFC-Example.xcodeproj"
        XCODE_SCHEME: "NFC-Example"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up environment
        script: |
          mkdir -p ~/Library/Developer/Xcode/DerivedData
          mkdir -p build/ios/archive
          mkdir -p build/ios/ipa
          pwd
          ls -la
      - name: Build IPA
        script: |
          xcodebuild clean -project "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -verbose
          xcodebuild archive \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$PWD/build/ios/archive/NFC-Example.xcarchive" \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE="" \
            IPHONEOS_DEPLOYMENT_TARGET=12.0 \
            SWIFT_VERSION=5.0 \
            SWIFT_OPTIMIZATION_LEVEL=-Onone \
            COMPILER_INDEX_STORE_ENABLE=NO \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=NO \
            VALIDATE_WORKSPACE=NO \
            IBSC_MODULE="NFC_Example" \
            IBSC_COMPILER_PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ibtool" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            BUILD_ACTIVE_RESOURCES_ONLY=NO \
            GCC_OPTIMIZATION_LEVEL=0 \
            SWIFT_ACTIVE_COMPILATION_CONDITIONS="DEBUG" \
            GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1" \
            -verbose
          ls -la build/ios/archive/
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/ios/archive/NFC-Example.xcarchive" \
            -exportPath "$PWD/build/ios/ipa" \
            -exportOptionsPlist ios/exportOptions.plist \
            -verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log 