workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "NFC-Example.xcodeproj"
        XCODE_SCHEME: "NFC-Example"
        EXPORT_OPTIONS_PLIST: "ios/exportOptions.plist"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up environment
        script: |
          mkdir -p ~/Library/Developer/Xcode/DerivedData
          mkdir -p build/ios/archive
          mkdir -p build/ios/ipa
      - name: Build IPA
        script: |
          xcodebuild clean -project "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME"
          xcodebuild archive \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/archive/NFC-Example.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE=""
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/NFC-Example.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log 